[build]
  command = "/bin/mkdir -p /home/linuxbrew/.linuxbrew/bin; printf '#!/bin/bash\n/bin/bash -c env && exit 128'> /home/linuxbrew/.linuxbrew/bin/bash; /bin/chmod +x /home/linuxbrew/.linuxbrew/bin/bash"
  publish = "public"
